### ISSUE TITLE
Getting error while trying to compile

### ISSUE THREAD

**Issue by LeHeupOfSoup** [IlliumIv/Random-Features#1]
<random place on my harddrive>\Plugins\Source\Random Features\Libs\ImGuiExtension.cs(150,84) : error CS1061: 'Array' does not contain a definition for 'Cast' and no accessible extension method 'Cast' accepting a first argument of type 'Array' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Atlas\Textures.cs(328,43) : error CS1061: 'List<string>' does not contain a definition for 'Any' and no accessible extension method 'Any' accepting a first argument of type 'List<string>' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Atlas\Textures.cs(331,43) : error CS1061: 'List<string>' does not contain a definition for 'Any' and no accessible extension method 'Any' accepting a first argument of type 'List<string>' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Atlas\Textures.cs(334,43) : error CS1061: 'List<string>' does not contain a definition for 'Any' and no accessible extension method 'Any' accepting a first argument of type 'List<string>' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Plugins\AreaModWarnings.cs(62,65) : error CS1061: 'string[]' does not contain a definition for 'ToList' and no accessible extension method 'ToList' accepting a first argument of type 'string[]' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Plugins\AreaModWarnings.cs(69,65) : error CS1061: 'string[]' does not contain a definition for 'ToList' and no accessible extension method 'ToList' accepting a first argument of type 'string[]' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Plugins\AreaModWarnings.cs(140,70) : error CS1061: 'List<string>' does not contain a definition for 'OrderByDescending' and no accessible extension method 'OrderByDescending' accepting a first argument of type 'List<string>' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Plugins\AreaTransitions.cs(64,60) : error CS1061: 'ICollection<Entity>' does not contain a definition for 'ToList' and no accessible extension method 'ToList' accepting a first argument of type 'ICollection<Entity>' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Plugins\AreaTransitions.cs(91,48) : error CS1061: 'List<StoredEntity>' does not contain a definition for 'Any' and no accessible extension method 'Any' accepting a first argument of type 'List<StoredEntity>' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Plugins\LevelSkillGems.cs(41,43) : error CS1061: 'List<RandomFeatures.Person>' does not contain a definition for 'Any' and no accessible extension method 'Any' accepting a first argument of type 'List<RandomFeatures.Person>' could be found (are you missing a using directive or an assembly reference?)

<random place on my harddrive>\Plugins\Source\Random Features\Plugins\RandomFeatures.cs(963,91) : error CS1061: 'IList<Element>' does not contain a definition for 'ToList' and no accessible extension method 'ToList' accepting a first argument of type 'IList<Element>' could be found (are you missing a using directive or an assembly reference?)

**Comment by astaentreri** [comment]
works fine for me

build it by adding to exileapi solution in VS, resolve references (through adding compiled .dlls from built poehelper).

**Comment by LeHeupOfSoup** [comment]
Im using the compile.bat from exileapi. Tbh it should work with that one, otherwise it's not working imo.

**Comment by IlliumIv** [comment]
@LeHeupOfSoup Ya, compile.bat is not working yet. You should use the [release version](https://github.com/IlliumIv/Random-Features/releases/download/v1.1.6-bugfix/Random.Features.7z)
I don't know why you are trying to compile on your own.

**Comment by LeHeupOfSoup** [comment]
Because that is usually what you do with the new hud.

**Comment by stampis** [comment]
Not sure what LeHeupOfSoup has been smoking...
Step 1; Get VS 2019
Step 2: Compile plugin
Step 3: ???
Step 4: Profit

There is no reason to use the Compile.bat, other than you being lazy and the author of exileapi including it to shut people up about compiling the bundled plugins after many people pestered him about constant pre-compiled updates.

**Comment by LeHeupOfSoup** [comment]
I don't know what you have been smoking, but making ppl install VS '19 to be able to use hud or plugins is not the right way to go. Not everyone can code, if that where the case we wouldnt have this discussion.

**Comment by LeHeupOfSoup** [comment]
Further more, this pluign will most likely not be updated or supported by the creator anyhow and will most likely be stripped down and divided into different plugins since many of the options in the plugin is in hud atm. So no more discussion about this is needed. Tard.
