### ISSUE TITLE
Skill Gem Leveling

### ISSUE THREAD

**Issue by astaentreri** [IlliumIv/Random-Features#3]
tosses errors when trying to set new key binding

![image](https://user-images.githubusercontent.com/19862908/65386653-e28b4680-dd3e-11e9-8e79-f6fec0c18f7d.png)

**Comment by IlliumIv** [comment]
@astaentreri Fix. Please download updated release.

But i never using auto skill up, so it can be broken.

**Comment by IlliumIv** [comment]
Yep, Skill Gem Leveling still broken. I'll try to fix it.
