### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Murdoc84** [IlliumIv/Random-Features#5]
Hiu, when i try to compile using CompilePlugins.bat i have errors, can you compile new changes and release it?

`Plugins \ Source \ Random Features \ Atlas \ Textures.cs (6,14): error CS0234: Type or namespace "Linq" does not appear in the "System" namespace (is there no missing reference to the set?)
Plugins \ Source \ Random Features \ Libs \ ImGuiExtension.cs (3,14): error CS0234: Type or namespace "Linq" does not appear in the "System" namespace (is there no missing reference to the set?)
Plugins \ Source \ Random Features \ Plugins \ AreaModWarnings.cs (7,14): error CS0234: Type or namespace "Linq" does not appear in the "System" namespace (is there no missing reference to the set?)
Plugins \ Source \ Random Features \ Plugins \ AreaTransitions.cs (4,14): error CS0234: Type or namespace "Linq" does not appear in the "System" namespace (is there no missing reference to the set?)
Plugins \ Source \ Random Features \ Plugins \ LevelSkillGems.cs (4,14): error CS0234: Type or namespace "Linq" does not appear in the "System" namespace (is there no missing reference to the set?)
Plugins \ Source \ Random Features \ Plugins \ RandomFeatures.cs (3,14): error CS0234: Type or namespace "Linq" does not appear in the "System" namespace (is there no missing reference to the set?)
Plugins \ Source \ Random Features \ Plugins \ LevelSkillGems.cs (259.20): error CS0246: Could not find type name or namespace "RangeNode <>" (no using directive or reference to set?)`

**Comment by skydrome** [comment]
add an include for ExileCore.Shared.Nodes

**Comment by Murdoc84** [comment]
I'll say this again, I use CompilePlugins.bat to compile it, not VS.

**Comment by IlliumIv** [comment]
Solved in 1.1.8.
